#ifndef IO_EXPORT_HPP
#define IO_EXPORT_HPP

#include <vector>
#include <string>
#include <array>
#include <fstream>
#include <cstring>
#include <cstdint>

namespace ioexp {

// Write binary STL from triangle soup
inline bool write_stl_binary(const std::string& path,
					  const std::vector<std::array<float,3>>& vertices,
					  const std::vector<std::array<uint32_t,3>>& faces) {
	std::ofstream os(path, std::ios::binary);
	if (!os) return false;
	char header[80]; std::memset(header, 0, 80); std::strncpy(header, "Generated by TOP3D_XL", 79);
	os.write(header, 80);
	uint32_t ntri = static_cast<uint32_t>(faces.size());
	os.write(reinterpret_cast<const char*>(&ntri), 4);
	for (auto f : faces) {
		float n[3] = {0,0,0};
		os.write(reinterpret_cast<char*>(n), 12);
		for (int i=0;i<3;i++) {
			auto v = vertices[f[i]];
			os.write(reinterpret_cast<const char*>(&v[0]), 12);
		}
		uint16_t attr = 0; os.write(reinterpret_cast<char*>(&attr), 2);
	}
	return true;
}

} // namespace ioexp

#endif



